Repository JunzhouLiu/BILIBILI-HELPER, pull requests merged in 2020-10, with the labels that each got.

#2 修改了图片中的顺序编号
  README.md
  docs/IMG/20201013134942.png
  docs/IMG/20201013210000.png
Labels: 完成 / Done

#17 Update README.md，修改 '浏览器缓存' 为 'Cookie'
  README.md
Labels: 完成 / Done

#19 充电留言请求体格式错误
  src/main/java/top/misec/task/DailyTask.java
Labels: 低优先级 / P3, 完成 / Done

#38 修改拼写错误
  README.md
Labels: 低优先级 / P3, 等待合并 / Pending Merge

#53 README.md 中英之间添加空格
  README.md
Labels: 低优先级 / P3, 完成 / Done
